<?php
declare(strict_types=1);

//Based on BSTD14 v3.1 Section 5.2

const QUESTION_COUNT_TOTAL=5; //is it correct??? 
const QUESTION_TYPES_TOTAL=2; //mcq, true/false

//HARDCODED VALUES FOR NOW UNDERSTANDING BUT CAN BE CHANGED DIRECTLY FROM HERE WHENEVER WE WANT


//QUESTION/ANSWER -> OPTIONS/TYPES/ID/TEXT -> LENGTH/TOTAL/MAX/MIN/COUNT
//HIERARCHICAL NAMING STANDARD


//FINALLY NEW CONSTANT DUE TO FEATURE FLAG HEHE

const QUESTION_ORDER_RANDOM_ENABLED_DEFAULT = false; //WILL BE FALSE BY DEFAULT


?>




